mode: parallel
containers:
  - address: http://192.168.31.233:5700
    username: admin
    password: admin
    weigth:  
    mode: parallel
    limit: 9999
theme: https://ghproxy.com/https://raw.githubusercontent.com/a251231/mass/main/panel/index.html #自定义二维码页面，支持本地、网络路径
static: ./static #静态文件 便于自定义二维码页面时，引入css、js等文件
master:  #管理员账户pin，有多个用'&'拼接
database:  #数据库位置，默认./.jdc.db
qywx_key:   #企业微信推送key
daily_push: #定时任务
resident: #均衡模式下所有容器共同的账号pin，有多个用'&'拼接。不建议填写，后续实现指定账号助力功能。
qbot_config_file: /root/dguebc-main/conf/qconfig.yaml
#自定义ua
user_agent:  
telegram_bot_token:   #telegram bot token
telegram_user_id:  #telegrame user id
qquid:  #接收通知的qq号
qqgid:  #监听的群
default_priority: #新用户默认优先级
no_ghproxy: false #更新资源是否不使用代理 默认false
qbot_public_mode: true   #qq机器人群聊模式，默认私聊模式  
daily_asset_push_cron: 0 9 * * * #日常资产推送时间
repos:
  - git: https://github.com/shufflewzc/faker2.git